version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: capistrano3-puma
    versions:
    - 5.0.2
  - dependency-name: rails-controller-testing
    versions:
    - 1.0.5
  - dependency-name: factory_bot_rails
    versions:
    - 6.1.0
  - dependency-name: bootsnap
    versions:
    - 1.5.1
    - 1.6.0
    - 1.7.1
  - dependency-name: repost
    versions:
    - 0.3.6
  - dependency-name: capistrano
    versions:
    - 3.15.0
  - dependency-name: haml
    versions:
    - 5.2.1
